### ISSUE TITLE
As a not-logged-in user, I should be able to search for listings by location

### ISSUE THREAD

**Issue by m-scherer** [dshinzie/crash_pad#5]
As a not logged in user
When I visit '/'
and I fill in 'search_keyword' with '80203'
and I click on 'Search'
I should be search_index_path
and I should see '80203'

**Comment by dshinzie** [comment]
visit '/'
fill_in 'search_keyword' with '80203'

click_on 'Search'

expect current_path to be search_index_path

expect page to have content '80203'
