### ISSUE TITLE
As a logged-in user, I should be able to search for listings by location

### ISSUE THREAD

**Issue by m-scherer** [dshinzie/crash_pad#6]
As a logged in user
When I visit '/'
and I fill_in 'search_keyword' with '80203'
click_on 'Search'
I should be at the search index path
and I should see 80203

**Comment by dshinzie** [comment]
visit '/'
fill_in 'search_keyword' with '80203'

click_on 'Search'

expect current_path to be search_index_path

expect page to have content '80203'
